stages:
  - build
  - deploy
  - maven_test

build:
  stage: build
  artifacts:
    paths:
      - target/grumbler-app.jar
    expire_in: 24h
  script:
    - mvn -e -B clean package
  when: manual
  tags:
    - mvn

deploy:
  stage: deploy
  provider: releases
  script:
    - scp -r target/grumbler-app.jar $USER_SSH@$IP_SSH_DEV:~/grumbler
  when: manual
  tags:
    - deploy

test_maven:
  stage: maven_test
  image: maven:3.5.3-jdk-8
  script:
    - mvn -e -B clean test -Dcheckstyle.skip
  when: manual
  tags:
    - maven